Project/Areas/Setup/Models/MenuTypeViewModel.cs
using Project.DAL;
using Project.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Areas.Setup.Models
{
    public class MenuTypeViewModel
    {
       
        public MenuTypeForm MenuTypeform { get; set; }

        public List<MenuType> MenuTypeList { get; set; }
    }

    public class MenuTypeForm
    {
        public int Id { get; set; }

        [Display(Name = "Menu Type")]
        [Required(ErrorMessage = "Please enter menu Type")]
        public string Name { get; set; }

        public bool IsDeleted { get; set; }
    }
}

Project/Areas/Setup/Controllers/MenuTypeController.cs
using Project.Areas.Setup.Models;
using Project.DAL;
using Project.Properties;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Areas.Setup.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class MenuTypeController : Controller
    {
        private PROEntities db = new PROEntities();
        public ActionResult Index()
        {
            try
            {
                MenuTypeViewModel model = new MenuTypeViewModel();
                model.MenuTypeList = db.MenuType.ToList();
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

        public ActionResult NewMenuType()
        {
            try
            {
                MenuTypeViewModel model = new MenuTypeViewModel();              
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });

            }
        }
       
        [HttpPost]
        public ActionResult NewMenuType(MenuTypeViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //check for duplicate
                    var validate = db.MenuType.Where(x => x.Name == model.MenuTypeform.Name).ToList();
                    if (validate.Any())
                    {                      
                        TempData["message"] = "The Menu Type Name " + model.MenuTypeform.Name.ToUpper() + " already exist. Please enter different name";
                        TempData["messageType"] = "danger";
                        return View(model);
                    }
                    MenuType add = new MenuType
                    {
                        Name = model.MenuTypeform.Name,
                        ModifiedBy = User.Identity.Name,
                        ModifiedDate = DateTime.Now,
                        IsDeleted = model.MenuTypeform.IsDeleted,
                      
                    };
                    db.MenuType.AddObject(add);
                    db.SaveChanges();
                    TempData["message"] = "" + model.MenuTypeform.Name.ToUpper() + " has been added successful.";
                    return RedirectToAction("Index");

                }               
                TempData["message"] = "Ops! Something went wrong. Please make sure you enter the menu type Name.";
                TempData["messageType"] = "danger";
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

        public ActionResult EditMenuType(int Id)
        {
            try
            {
                var GetMenuType = db.MenuType.Where(x => x.Id == Id).FirstOrDefault();
                if (GetMenuType == null)
                {

                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index");
                }
                MenuTypeViewModel model = new MenuTypeViewModel();
                model.MenuTypeform = new MenuTypeForm();
                model.MenuTypeform.Id = GetMenuType.Id;
                model.MenuTypeform.Name = GetMenuType.Name;
                model.MenuTypeform.IsDeleted = GetMenuType.IsDeleted;
         
         
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }


        [HttpPost]
        public ActionResult EditMenuType(MenuTypeViewModel model)
        {
            try
            {
                var GetMenuType = db.MenuType.Where(x => x.Id == model.MenuTypeform.Id).FirstOrDefault();
                if (GetMenuType == null)
                {
                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index");
                }
                GetMenuType.Name = model.MenuTypeform.Name;
                GetMenuType.IsDeleted = model.MenuTypeform.IsDeleted;
                GetMenuType.ModifiedBy = User.Identity.Name;
                GetMenuType.ModifiedDate = DateTime.Now;
               
                db.SaveChanges();
                TempData["message"] = "The Size name " + model.MenuTypeform.Name.ToUpper() + " has been updated successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

    }
}

Project/Areas/Setup/Views/MenuType/EditMenuType.cshtml
@model Project.Areas.Setup.Models.MenuTypeViewModel

@{
    ViewBag.Title = "Edit Menu Type";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">Edit Menu Type</a> </li>
        </ul>
    </div>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>
                    Edit Menu Type

                </h4>
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("EditMenuType", "MenuType", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x=>x.MenuTypeform.Id)

                    <div class="form-group">
                        @Html.Label("Menu Type Name", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.MenuTypeform.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MenuTypeform.Name, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Is Deleted?", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(m => m.MenuTypeform.IsDeleted)
                        </div>
                    </div>




                    <div class="form-actions">
                        <a href="@Url.Action("Index", "MenuType", new { area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });
    </script>
}

Project/Areas/Setup/Views/MenuType/Index.cshtml
@model Project.Areas.Setup.Models.MenuTypeViewModel
@using Project.HtmlHelpers
@{
    ViewBag.Title = "Menu Type Management";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">Menu Type Management</a> </li>
        </ul>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <div class="widget-header">
            <a class="btn btn-xs btn-warning" href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a>   @Html.ActionLink("Create New", "NewMenuType", null, new { @class = "btn btn-xs btn-success" }) 
        </div>
        <br />

        <div class="widget-content">
            <table class="table table-striped table-bordered table-hover table-checkable datatable dataTable">
                <thead>
                    <tr style="font-size: 12px;">
                        <th>S/N</th>
                        <th>Name</th>                       
                        <th>Modified By</th>
                        <th>Modified Date</th>
                        <th>Is Deleted</th>
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model.MenuTypeList.Count != 0)
                    {
                        int i = 0;
                        foreach (var item in Model.MenuTypeList)
                        {
                            ++i;
                            <tr style="font-size: 12px;">
                                <td>
                                    @i
                                </td>
                                <td>@item.Name</td>
                               
                                <td>@item.ModifiedBy</td>
                                <td>@item.ModifiedDate.ToShortDateString()</td>
                                <td>
                                    @if (item.IsDeleted == true)
                                    {
                                        <span class="label label-success"> <strong>Yes</strong></span>
                                    }
                                    else
                                    {
                                        <span class="label label-danger"> <strong>No</strong></span>
                                    }

                                </td>
                                <td>
                                    <a class="btn btn-xs btn-danger" href="@Url.Action("EditMenuType", "MenuType", new { area="Setup", Id = item.Id})">Edit</a>
                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="8">No Records Found!...</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>


    </div>
</div>

@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    <script>
        "use strict";

    </script>
}

Project/Areas/Setup/Views/MenuType/NewMenuType.cshtml
@model Project.Areas.Setup.Models.MenuTypeViewModel

@{
    ViewBag.Title = "New Menu Type";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">New Menu Type</a> </li>
        </ul>
    </div>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>
                    New Menu Type

                </h4>
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("NewMenuType", "MenuType", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {

                    @Html.AntiForgeryToken()

                    

                    <div class="form-group">
                        @Html.Label("Menu Type Name", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.MenuTypeform.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MenuTypeform.Name, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Is Deleted?", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(m => m.MenuTypeform.IsDeleted)
                        </div>
                    </div>




                    <div class="form-actions">
                        <a href="@Url.Action("Index", "MenuType", new { area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });
    </script>
}