Project/Areas/Setup/Models/ProductColorViewModel.cs
using Project.DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Areas.Setup.Models
{
    public class ProductColorViewModel
    {
        public List<ProductColor> ProductColorlist { get; set; }
        public ProductColorForm Productcolorform { get; set; }

        public ProductColor Productcolor { get; set; }
    }

    public class ProductColorForm
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter your Store name")]
        [Display(Name = "Color Name")]
        public string Name { get; set; }      

        public bool IsDeleted { get; set; }

    }
}

Project/Areas/Setup/Controllers/ProductColorController.cs
using Project.Areas.Setup.Models;
using Project.DAL;
using Project.Properties;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Areas.Setup.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ProductColorController : Controller
    {
        //
        // GET: /Setup/ProductColor/
        private PROEntities db = new PROEntities();

        public ActionResult Index()
        {
            try
            {
                ProductColorViewModel model = new ProductColorViewModel();
                model.ProductColorlist = db.ProductColor.ToList();               
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

        public ActionResult NewProductColor()
        {
            try
            {
                ProductColorViewModel model = new ProductColorViewModel();
                return View(model);
            }
            catch(Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });

            }
        }

        [HttpPost]
        public ActionResult NewProductColor(ProductColorViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //check for duplicate
                    var validate = db.ProductColor.Where(x => x.Name == model.Productcolorform.Name).ToList();
                    if (validate.Any())
                    {
                        TempData["message"] = "The Color Name " + model.Productcolorform.Name + " already exist. Please enter different name";
                        TempData["messageType"] = "danger";
                        return View(model);
                    }
                    ProductColor add = new ProductColor
                    {
                        Name = model.Productcolorform.Name,
                        ModifiedBy = User.Identity.Name,
                        ModifiedDate = DateTime.Now,
                        IsDeleted = model.Productcolorform.IsDeleted
                    };
                    db.ProductColor.AddObject(add);
                    db.SaveChanges();
                    TempData["message"] = "" + model.Productcolorform.Name + " has been added successful.";
                    return RedirectToAction("Index");

                }
                TempData["message"] = "Ops! Something went wrong. Please make sure you enter the Color Name.";
                TempData["messageType"] = "danger";
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }



        public ActionResult EditProductColor(int Id)
        {
            try
            {
                var GetColor = db.ProductColor.Where(x => x.Id == Id).FirstOrDefault();
                if (GetColor == null)
                {
                    
                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index");
                }
                ProductColorViewModel model = new ProductColorViewModel();
                model.Productcolorform = new  ProductColorForm();
                model.Productcolorform.Id = GetColor.Id;
                model.Productcolorform.Name = GetColor.Name;
                model.Productcolorform.IsDeleted = GetColor.IsDeleted;
                return View(model);
            }
            catch(Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }


        [HttpPost]
        public ActionResult EditProductColor(ProductColorViewModel model)
        {
            try
            {
                var getColor = db.ProductColor.Where(x => x.Id == model.Productcolorform.Id).FirstOrDefault();
                if(getColor==null)
                {
                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index");
                }
                getColor.Name = model.Productcolorform.Name;
                getColor.IsDeleted = model.Productcolorform.IsDeleted;
                getColor.ModifiedBy = User.Identity.Name;
                getColor.ModifiedDate = DateTime.Now;
                db.SaveChanges();
                TempData["message"] = "The Color name " + model.Productcolorform.Name + " has been updated successfully.";                
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

    }
}

Project/Areas/Setup/Views/ProductColor/EditProductColor.cshtml
@model Project.Areas.Setup.Models.ProductColorViewModel

@{
    ViewBag.Title = "Edit Product Color";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">Edit Product Color</a> </li>
        </ul>
    </div>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>
                    Edit Product Color

                </h4>
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("EditProductColor", "ProductColor", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x=>x.Productcolorform.Id)

                    <div class="form-group">
                        @Html.Label("Name", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.Productcolorform.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productcolorform.Name, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Is Deleted?", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(m => m.Productcolorform.IsDeleted)
                        </div>
                    </div>


                    <div class="form-actions">
                        <a href="@Url.Action("Index", "ProductColor", new { area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });
    </script>
}

Project/Areas/Setup/Views/ProductColor/Index.cshtml
@model Project.Areas.Setup.Models.ProductColorViewModel
@using Project.HtmlHelpers
@{
    ViewBag.Title = "Product Color List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";
}
@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)"></a>Product Color List </li>
        </ul>
    </div>
}


<div class="row">
    <div class="col-md-12">
        <div class="widget-header">
            <h4></h4>
        </div>
        <div class="widget-content">
            <div class="row" style="margin-bottom: 10px;">
                <div class="col-md-12">
                    <a class="btn btn-xs btn-warning" href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a>   @Html.ActionLink("Create New", "NewProductColor", null, new { @class = "btn btn-xs btn-success" })
                </div>

            </div>

            <table class="table table-striped table-bordered table-hover table-checkable datatable dataTable">
                <thead>
                    <tr>
                        <th>
                            S/N
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Modified By
                        </th>
                        <th>
                            Modified Date
                        </th>
                        <th>
                            Is Deleted
                        </th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.ProductColorlist.Count != 0)
                    {

                        int i = 0;
                        foreach (var item in Model.ProductColorlist)
                        {
                            ++i;
                            <tr>
                                <td>
                                    @i

                                </td>
                                <td>
                                    @item.Name
                                </td>

                                <td>
                                    @item.ModifiedBy
                                </td>
                                <td>
                                    @item.ModifiedDate
                                </td>


                                <td>
                                    @if (item.IsDeleted == true)
                                    {
                                        <span class="label label-info">Yes</span>
                                    }
                                    else
                                    {
                                        <span class="label label-warning">No</span>
                                    }

                                </td>

                                <td>
                                    <a class="btn btn-xs btn-danger" href="@Url.Action("EditProductColor", "ProductColor", new { area="Setup", Id = item.Id})">Edit</a>
                                </td>
                            </tr>

                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="99">No Records Found!...</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    <script>
        "use strict";

    </script>
}

Project/Areas/Setup/Views/ProductColor/NewProductColor.cshtml
@model Project.Areas.Setup.Models.ProductColorViewModel

@{
    ViewBag.Title = "New Product Color";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">New Product Color</a> </li>
        </ul>
    </div>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>
                    New Product Color

                </h4>
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("NewProductColor", "ProductColor", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {

                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        @Html.Label("Name", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.Productcolorform.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productcolorform.Name, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Is Deleted?", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(m => m.Productcolorform.IsDeleted)
                        </div>
                    </div>




                    <div class="form-actions">
                        <a href="@Url.Action("Index", "ProductColor", new { area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });
    </script>
}