Project/Areas/Setup/Models/ProductManagementViewModel.cs
using Project.DAL;
using Project.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Areas.Setup.Models
{
    public class ProductManagementViewModel
    {
        //Tables Mostly Index Page
        public List<ProductCategory> CategoryList { get; set; }
        public List<StoreProduct> ProductList { get; set; }

        public StoreProduct product { get; set; }

        public ProductCategory category { get; set; }

        //Dropdown list
        public List<IntegerSelectListItem> BrandList { get; set; }
        public List<IntegerSelectListItem> PackageTyeList { get; set; }
        public List<IntegerSelectListItem> SubcategoryList { get; set; }
        
        public List<IntegerSelectListItem> ChildcategoryList { get; set; }


        public Store store { get; set; }
        public ProductForm Productform { get; set; }
        public string documentPath { get; set; }

        public string p1 { get; set; }
        public string p2 { get; set; }
        public string p3 { get; set; }


        //Available colors
        public List<ProductColor> AllColor { get; set; }
       // [Required(ErrorMessage = "Please select a color to add")]
        public List<string> ColorUsed { get; set; }
        public List<string> ColorSelected { get; set; }
        public List<string> ColorUsedTex { get; set; }


        //granted colors
        public List<ProductColor> AllSelectColor { get; set; }
     //   [Required(ErrorMessage = "Please select a color to remove")]
        public List<string> GrantedColorUsed { get; set; }
        public List<string> GrantedColorSelected { get; set; }
        public List<string> GrantedColorUsedTex { get; set; }

        
        public List<IntegerSelectListItem> AllSizeType { get; set; }
        public int SizeTypeId { get; set; }
        public List<Size> AllGrantedSize { get; set; }

        //Available size
        public List<Size> AllSize { get; set; }
       // [Required(ErrorMessage = "Please select a size to add")]
        public List<string> SizeUsed { get; set; }
        public List<string> SizeSelected { get; set; }
        public List<string> sizeUsedTex { get; set; }


        //granted size
        public List<Size> AllSelectedSize { get; set; }
       // [Required(ErrorMessage = "Please select a size to remove")]
        public List<string> GrantedSizeUsed { get; set; }
        public List<string> GrantedSizeSelected { get; set; }
        public List<string> GrantedSizeUsedTex { get; set; }

    }
    public class ProductForm
    {
        public int Id { get; set; }

        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "Please enter The Product Name")]
        public string Name { get; set; }

        [Display(Name = "Package Type")]
        [Required(ErrorMessage = "Please select the package Type")]
        public int ShippingCostId { get; set; }

        [Display(Name = "Weight(In KG)")]
        [Required(ErrorMessage = "Please enter The Product Weight")]
        public int Weight { get; set; }

        [Display(Name = "Product Description")]
        [Required(ErrorMessage = "Please enter The Product Description")]
        public string Description { get; set; }

        [Display(Name = "Acutal Price")]
        [Required(ErrorMessage = "Please enter Actual price")]
        public decimal AcutalPrice { get; set; }

        [Display(Name = "Discount Price")]
        [Required(ErrorMessage = "Please enter Discount price")]
        public decimal DiscountPrice { get; set; }

        [Display(Name = "Quantity")]
        [Required(ErrorMessage = "Please enter Quantity")]
        public int Quantity { get; set; }

        public int NewQuantity { get; set; }

        [Display(Name = "Re-order level")]
        [Required(ErrorMessage = "Please enter Re-order Level")]
        public int ReorderLevel { get; set; }

        [Display(Name = "Photo 1")]
       // [Required(ErrorMessage = "Please Upload Photo 1")]
        public HttpPostedFileBase Photo1 { get; set; }

        [Display(Name = "Photo 2")]      
        public HttpPostedFileBase Photo2 { get; set; }

        [Display(Name = "Photo 3")]
        public HttpPostedFileBase Photo3 { get; set; }

        [Display(Name = "Brand")]
        [Required(ErrorMessage = "Please select a Brand")]
        public int BrandId { get; set; }

        [Display(Name = "Has Color")]
        public bool HasColor { get; set; }

        [Display(Name = "Has Size")]
        public bool HasSize { get; set; }

        [Display(Name = "Has Sales")]
        public bool HasSales { get; set; }

        [Display(Name = "Sub Category")]
        [Required(ErrorMessage = "Please select a Sub Category")]
        public int ProductSubCategoryId { get; set; }

        [Display(Name = "Child Category")]
        [Required(ErrorMessage = "Please select a Child Category")]
        public int ProductChildCategoryId { get; set; }

        public bool IsDeleted { get; set; }
        public int CategoryId { get; set; }
    }
}

Project/Areas/Setup/Controllers/ProductManagementController.cs
using Project.Areas.Setup.Models;
using Project.DAL;
using Project.Models;
using Project.Properties;
using Project.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Roles = System.Web.Security.Roles;

namespace Project.Areas.Setup.Controllers
{
    [Authorize(Roles = "Administrator, Store Admin, Product Manager")]
    public class ProductManagementController : Controller
    {
        //
        // GET: /Setup/ProductManagement/
        Backbone services = new Backbone();
        private PROEntities db = new PROEntities();
        private ProcessUtility util = new ProcessUtility();

        private Store storeDetails()
        {
            try
            {
                var username = Membership.GetUser().UserName;
                var user = db.Users.Where(x => x.UserName == username).FirstOrDefault();

                return user.Store.FirstOrDefault();
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                return null;
            }
        }

        public ActionResult Index(Guid Id)
        {
            try
            {
                var storeDetail = storeDetails();
                if (!Roles.IsUserInRole("Administrator"))
                {
                    if (storeDetail == null)
                    {
                        Elmah.ErrorSignal.FromCurrentContext().Raise(new Exception("Unauthorised Access"));
                        TempData["message"] = "Unauthorised Access";
                        return RedirectToAction("Index", "Store", new { area = "Setup" });
                    }
                }



                ProductManagementViewModel model = new ProductManagementViewModel();
                model.store = Backbone.GetStore(db, Id);
                if (model.store == null)
                {

                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index", "Store", new { area = "Setup" });
                }
                model.CategoryList = model.store.ProductCategory.ToList();
                TempData["message"] = "Add Product using the Category below. To Add more Category use the back button.";
                TempData["messageType"] = "warning";
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

        public ActionResult ProductList(Guid Id, int CategoryId)
        {
            try
            {
                var storeDetail = storeDetails();
                if (!Roles.IsUserInRole("Administrator"))
                {
                    if (storeDetail == null)
                    {
                        Elmah.ErrorSignal.FromCurrentContext().Raise(new Exception("Unauthorised Access"));
                        TempData["message"] = "Unauthorised Access";
                        return RedirectToAction("Index", "Store", new { area = "Setup" });
                    }
                }
                ProductManagementViewModel model = new ProductManagementViewModel();
                model.store = Backbone.GetStore(db, Id);
                if (model.store == null)
                {
                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index", "Store", new { area = "Setup" });
                }
                model.ProductList = model.store.StoreProduct.Where(x=>x.ProductCategoryId== CategoryId).ToList();
                model.documentPath = Properties.Settings.Default.ProductImagePath;
                var cate = model.store.ProductCategory.Where(x => x.Id == CategoryId).FirstOrDefault();
                model.category = cate;
                return View(model);
            }
            catch(Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

        public ActionResult NewProduct(Guid Id, int CategoryId)
        {
            try
            {
                var storeDetail = storeDetails();
                if (!Roles.IsUserInRole("Administrator"))
                {
                    if (storeDetail == null)
                    {
                        Elmah.ErrorSignal.FromCurrentContext().Raise(new Exception("Unauthorised Access"));
                        TempData["message"] = "Unauthorised Access";
                        return RedirectToAction("Index", "Store", new { area = "Setup" });
                    }
                }

                ProductManagementViewModel model = new ProductManagementViewModel();                
                model.store = Backbone.GetStore(db, Id);
                if (model.store == null)
                {
                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index", "Store", new { area = "Setup" });
                }
                var cate = model.store.ProductCategory.Where(x => x.Id == CategoryId).FirstOrDefault();
                model.Productform = new ProductForm();
                model.Productform.CategoryId = CategoryId;
                model.BrandList = (from s in cate.ProductBrand where s.IsDeleted == false select new IntegerSelectListItem() { Text = s.Name, Value = s.Id }).ToList<IntegerSelectListItem>();
                model.SubcategoryList = (from s in model.store.ProductSubCategory where s.IsDeleted == false && s.ProductCategoryId== CategoryId select new IntegerSelectListItem() { Text = s.Name, Value = s.Id }).ToList<IntegerSelectListItem>();
                model.ChildcategoryList = (from s in model.store.ProductChildCategory where s.IsDeleted == false select new IntegerSelectListItem() { Text = s.Name, Value = s.Id }).ToList<IntegerSelectListItem>();
                model.PackageTyeList = (from s in db.ShippingCost where s.IsDeleted == false select new IntegerSelectListItem() { Text = s.Name, Value = s.Id }).ToList<IntegerSelectListItem>();
                model.category = cate;
                return View(model);
            }
            catch(Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });

            }
        }


        [HttpPost]
        public ActionResult GetChildId(int SubCategoryId)
        {
            var storeDetail = storeDetails();
            if (Roles.IsUserInRole("Administrator"))
            {
                List<IntegerSelectListItem> list = (from d in db.ProductChildCategory where d.ProductSubCategoryId == SubCategoryId orderby d.Name select new IntegerSelectListItem() { Text = d.Name, Value = d.Id }).ToList<IntegerSelectListItem>();
                return base.Json(list);
            }
            else
            {
                List<IntegerSelectListItem> list = (from d in storeDetail.ProductChildCategory where d.ProductSubCategoryId == SubCategoryId orderby d.Name select new IntegerSelectListItem() { Text = d.Name, Value = d.Id }).ToList<IntegerSelectListItem>();
                return base.Json(list);
            }



        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult NewProduct(ProductManagementViewModel model)
        {
            try
            {
                var storeDetail = storeDetails();
                if (!Roles.IsUserInRole("Administrator"))
                {
                    if (storeDetail == null)
                    {
                        Elmah.ErrorSignal.FromCurrentContext().Raise(new Exception("Unauthorised Access"));
                        TempData["message"] = "Unauthorised Access";
                        return RedirectToAction("Index", "Store", new { area = "Setup" });
                    }
                }

                model.store = Backbone.GetStore(db, model.store.ProcessInstaceId);
                if (model.store == null)
                {
                    TempData["message"] = "Store object is empty";
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index", "Store", new { area = "Setup" });
                }
                if (ModelState.IsValid)
                {
                    //check for duplicate
                    
                    var validate = model.store.StoreProduct.Where(x => x.Name == model.Productform.Name).ToList();
                    if (validate.Any())
                    {
                        TempData["message"] = "The Name " + model.Productform.Name + " already exist. Please enter different name";
                        TempData["messageType"] = "danger";

                        var cate1 = db.ProductCategory.Where(x => x.Id == model.Productform.CategoryId).FirstOrDefault();
                        model.BrandList = (from s in cate1.ProductBrand where s.IsDeleted == false select new IntegerSelectListItem() { Text = s.Name, Value = s.Id }).ToList<IntegerSelectListItem>();

Project/Areas/Setup/Views/ProductManagement/NewProduct.cshtml
@model Project.Areas.Setup.Models.ProductManagementViewModel
@{
    ViewBag.Title = Model.store.Name + " New Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";
}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li><i class="icon-home"></i><a href="@Url.Action("Index", "Home", new { area = "Admin" })">Dashboard</a> </li>
            <li><i class="current"></i><a href="javascript: return void(0)">@Model.store.Name  New Product</a> </li>


        </ul>
    </div>
}
<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
               <h4><i class="icon-reorder"></i>You are adding a product for under @Model.category.Name.ToUpper() Category :</h4> <h4 style="color:red">  Please note fileds with red * is required. </h4> 
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("NewProduct", "ProductManagement", new { Id = Model.store.ProcessInstaceId, CategoryId = Model.Productform.CategoryId }, FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {
                    @Html.HiddenFor(x => x.store.ProcessInstaceId)
                    @Html.HiddenFor(x => x.Productform.CategoryId)
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    <div class="form-group">
                        @Html.Label("Product Name", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.Productform.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.Name, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Package Type", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.DropDownListFor(m => m.Productform.ShippingCostId, new SelectList(Model.PackageTyeList, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.ShippingCostId, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Weight(In kg)", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.Productform.Weight, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.Weight, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Brand", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.DropDownListFor(m => m.Productform.BrandId, new SelectList(Model.BrandList, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.BrandId, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Discount Price", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.Productform.DiscountPrice, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.DiscountPrice, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Actual Price", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.Productform.AcutalPrice, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.AcutalPrice, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Quantity", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.Productform.Quantity, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.Quantity, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Re-order Level", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.Productform.ReorderLevel, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.ReorderLevel, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Sub Category", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.DropDownListFor(m => m.Productform.ProductSubCategoryId, new SelectList(Model.SubcategoryList, "Value", "Text"), "select One", new { @class = "form-control", onChange = "GetAllChild(this)" })
                            @Html.ValidationMessageFor(model => model.Productform.ProductSubCategoryId, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Child Category", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-2">
                            @Html.DropDownListFor(m => m.Productform.ProductChildCategoryId, new SelectList(Model.ChildcategoryList, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.ProductChildCategoryId, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Photo 1", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(x => Model.Productform.Photo1, new { type = "file", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Productform.Photo1, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Photo 2", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(x => Model.Productform.Photo2, new { type = "file", @class = "form-control" })
                            @*@Html.ValidationMessageFor(model => model.Productform.Photo2, null, new { @style = "color:red" })*@
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Photo 3", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(x => Model.Productform.Photo3, new { type = "file", @class = "form-control" })
                            @*@Html.ValidationMessageFor(model => model.Productform.Photo3, null, new { @style = "color:red" })*@
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Has Color", new { @class = "col-md-2 control-label" })
                        <div class="col-md-1">
                            @Html.CheckBoxFor(x => Model.Productform.HasColor, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Has Size", new { @class = "col-md-2 control-label" })
                        <div class="col-md-1">
                            @Html.CheckBoxFor(x => Model.Productform.HasSize, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Has Sales", new { @class = "col-md-2 control-label" })
                        <div class="col-md-1">
                            @Html.CheckBoxFor(x => Model.Productform.HasSales, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Description", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(x => Model.Productform.Description, new { @class = "col-md-10 form-control" })

                        </div>
                    </div>

                    <div class="form-actions">
                        <a href="@Url.Action("ProductList", "ProductManagement", new {Id=Model.store.ProcessInstaceId,CategoryId=Model.Productform.CategoryId, area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    @Scripts.Render("~/Content/Backend/vendors/tinymce/tinymce.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });

        function getchild(e) {
            var subcategoryId = $(e).val();

            var currentRequest = null;
            var currentRequest = $.ajax({
                url: '@Url.Action("GetChildId", "ProductManagement")',
                dataType: 'json',
                type: 'POST',
                data: { SubCategoryId: subcategoryId },
                beforeSend: function () {
                    if (currentRequest != null) {
                        currentRequest.abort();
                    }
                },
                success: function (msg) {
                    $("#Productform_ProductChildCategoryId").html("");
                    $.each(msg, function (index, element) {
                        $("#Productform_ProductChildCategoryId").append('<option  value="' + element.Value + '">' + element.Text + '</option>');
                    });
                },
                error: function (errmsg) { }
            });
        }

        function GetAllChild(e) {
            getchild(e);

        }



        tinymce.init({
            selector: "textarea",
            mode: "exact",
            elements: "Productform_Description",
            theme: "modern",




            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor "
            ],
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            toolbar2: "print preview media | forecolor backcolor emoticons",
            image_advtab: true,
            templates: [
                { title: 'Test template 1', content: 'Test 1' },
                { title: 'Test template 2', content: 'Test 2' }
            ]
        });
    </script>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>