Project/Areas/Setup/Models/ShippingCostViewModel.cs
using Project.DAL;
using Project.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Areas.Setup.Models
{
    public class ShippingCostViewModel
    {
        public ShippingCostForm shippingCostForm { get; set; }

        public List<ShippingCost> Rows { get; set; }
    }

    public class ShippingCostForm
    {
        public int Id { get; set; }

        [Display(Name = "Package Type")]
        [Required(ErrorMessage = "Please enter Package Type")]
        public string Name { get; set; }

        [Display(Name = "Price Per kg")]
        [Required(ErrorMessage = "Please enter Price per kg")]
        public decimal Fees { get; set; }

        public bool IsDeleted { get; set; }
    }
}

Project/Areas/Setup/Controllers/ShippingCostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Areas.Setup.Models;
using Project.DAL;
using Project.Models;
using Project.Properties;

namespace Project.Areas.Setup.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ShippingCostController : Controller
    {
        //
        // GET: /Setup/ShippingCost/
        private PROEntities db = new PROEntities();

        public ActionResult Index()
        {
            try
            {
                ShippingCostViewModel model = new ShippingCostViewModel();
                model.Rows = db.ShippingCost.ToList();
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }



        public ActionResult NewShippingCost()
        {
            try
            {
                ShippingCostViewModel model = new ShippingCostViewModel();
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });

            }
        }


        [HttpPost]
        public ActionResult NewShippingCost(ShippingCostViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //check for duplicate
                    var validate = db.ShippingCost.Where(x => x.Name == model.shippingCostForm.Name).ToList();
                    if (validate.Any())
                    {
                      
                        TempData["message"] = "The Package Type " + model.shippingCostForm.Name.ToUpper() + " already exist. Please enter different name";
                        TempData["messageType"] = "danger";
                        return View(model);
                    }
                    ShippingCost add = new ShippingCost
                    {
                        Name = model.shippingCostForm.Name,
                        Fees = model.shippingCostForm.Fees,
                        ModifiedBy = User.Identity.Name,
                        ModifiedDate = DateTime.Now,
                        IsDeleted = model.shippingCostForm.IsDeleted,
                       
                    };
                    db.ShippingCost.AddObject(add);
                    db.SaveChanges();
                    TempData["message"] = "" + model.shippingCostForm.Name.ToUpper() + " has been added successful.";
                    return RedirectToAction("Index");

                }               
                TempData["message"] = "Ops! Something went wrong. Please make sure you enter all fileds.";
                TempData["messageType"] = "danger";
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }


        public ActionResult EditShippingCost(int Id)
        {
            try
            {
                var GetCost = db.ShippingCost.Where(x => x.Id == Id).FirstOrDefault();
                if (GetCost == null)
                {

                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index");
                }
                ShippingCostViewModel model = new ShippingCostViewModel();
                model.shippingCostForm = new  ShippingCostForm();
                model.shippingCostForm.Id = GetCost.Id;
                model.shippingCostForm.Name = GetCost.Name;
                model.shippingCostForm.Fees = GetCost.Fees;
                model.shippingCostForm.IsDeleted = GetCost.IsDeleted;                
                return View(model);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }


        [HttpPost]
        public ActionResult EditShippingCost(ShippingCostViewModel model)
        {
            try
            {
                var GetCost = db.ShippingCost.Where(x => x.Id == model.shippingCostForm.Id).FirstOrDefault();
                if (GetCost == null)
                {
                    TempData["message"] = Settings.Default.GenericExceptionMessage;
                    TempData["messageType"] = "danger";
                    return RedirectToAction("Index");
                }
                GetCost.Name = model.shippingCostForm.Name;
                GetCost.IsDeleted = model.shippingCostForm.IsDeleted;
                GetCost.ModifiedBy = User.Identity.Name;
                GetCost.ModifiedDate = DateTime.Now;               
                db.SaveChanges();
                TempData["message"] = "The package type " + model.shippingCostForm.Name.ToUpper() + " has been updated successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["message"] = Settings.Default.GenericExceptionMessage;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
            }
        }

    }

   
}

Project/Areas/Setup/Views/ShippingCost/EditShippingCost.cshtml
@model Project.Areas.Setup.Models.ShippingCostViewModel

@{
    ViewBag.Title = "Edit Shipping Cost";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">Edit Shipping Cost</a> </li>
        </ul>
    </div>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>
                    Edit Shipping Cost

                </h4>
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("EditShippingCost", "ShippingCost", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.shippingCostForm.Id)


                    <div class="form-group">
                        @Html.Label("Package Type", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.shippingCostForm.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.shippingCostForm.Name, null, new { @style = "color:red" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Price Per kg", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.shippingCostForm.Fees, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.shippingCostForm.Fees, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Is Deleted?", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(m => m.shippingCostForm.IsDeleted)
                        </div>
                    </div>




                    <div class="form-actions">
                        <a href="@Url.Action("Index", "ShippingCost", new { area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });
    </script>
}

Project/Areas/Setup/Views/ShippingCost/Index.cshtml
@model Project.Areas.Setup.Models.ShippingCostViewModel
@using Project.HtmlHelpers
@{
    ViewBag.Title = "Shipping Cost List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";
}
@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)"></a>Shipping Cost List </li>
        </ul>
    </div>
}


<div class="row">
    <div class="col-md-12">
        <div class="widget-header">
            <h4></h4>
        </div>
        <div class="widget-content">
            <div class="row" style="margin-bottom: 10px;">
                <div class="col-md-12">
                    <a class="btn btn-xs btn-warning" href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a>   @Html.ActionLink("Create New", "NewShippingCost", null, new { @class = "btn btn-xs btn-success" })
                </div>

            </div>
            <table class="table table-striped table-bordered table-hover table-checkable datatable dataTable">
                <thead>
                    <tr>
                        <th>
                            S/N
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Price per kg
                        </th>
                        <th>
                            Modified By
                        </th>
                        <th>
                            Modified Date
                        </th>
                        <th>
                            Is Deleted
                        </th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Rows.Count != 0)
                    {

                        int i = 0;
                        foreach (var item in Model.Rows)
                        {
                            ++i;
                    <tr>
                        <td>
                            @i

                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            ₦@String.Format("{0:n0}", item.Fees)
                        </td>
                        <td>
                            @item.ModifiedBy
                        </td>
                        <td>
                            @item.ModifiedDate
                        </td>


                        <td>
                            @if (item.IsDeleted == true)
                            {
                                <span class="label label-info">Yes</span>
                            }
                            else
                            {
                                <span class="label label-warning">No</span>
                            }

                        </td>

                        <td>
                            <a class="btn btn-xs btn-danger" href="@Url.Action("EditShippingCost", "ShippingCost", new { area="Setup", Id = item.Id})">Edit</a>
                        </td>
                    </tr>

                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="99">No Records Found!...</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    <script>
        "use strict";

    </script>
}

Project/Areas/Setup/Views/ShippingCost/NewShippingCost.cshtml
@model Project.Areas.Setup.Models.ShippingCostViewModel

@{
    ViewBag.Title = "New Shipping Cost";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.IsGreetings = "true";}

@section Crumbs{
    <div class="crumbs">

        <ul class="breadcrumb" id="breadcrumbs">
            <li> <i class="icon-home"></i> <a href="@Url.Action("Index", "Dashboard", new { area="Admin"})">Dashboard</a> </li>
            <li class="current"> <a title="" href="javascript: return void(0)">New Shipping Cost</a> </li>
        </ul>
    </div>
}
<style>
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>
                    Shipping Cost

                </h4>
            </div>
            <div class="widget-content">
                @using (Html.BeginForm("NewShippingCost", "ShippingCost", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal row-border" }))
                {

                    @Html.AntiForgeryToken()


                    <div class="form-group">
                        @Html.Label("Package Type", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.shippingCostForm.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.shippingCostForm.Name, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Price Per kg", new { @class = "col-md-2 control-label required" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.shippingCostForm.Fees, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.shippingCostForm.Fees, null, new { @style = "color:red" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Is Deleted?", new { @class = "col-md-2 control-label" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(m => m.shippingCostForm.IsDeleted)
                        </div>
                    </div>




                    <div class="form-actions">
                        <a href="@Url.Action("Index", "ShippingCost", new { area="Setup"})" class="btn btn-success btn-xs"><< Back to List </a>
                        <input type="submit" class="btn btn-warning btn-xs pull-right" value="Save" />
                    </div>
                }
            </div>

        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/Content/Backend/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/tabletools/TableTools.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/colvis/ColVis.min.js")
    @Scripts.Render("~/Content/Backend/plugins/datatables/DT_bootstrap.js")
    @Scripts.Render("~/Content/Backend/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")
    <script>
        "use strict";
        $(document).ready(function () {
            $(".datepicker-issueddate").datepicker({
                defaultDate: +7,
                showOtherMonths: true,
                autoSize: false,
                maxDate: new Date(),
                appendText: '<span class="help-block">(yyyy-mm-dd)</span>',
                dateFormat: "yy-mm-dd"
            });

        });
    </script>
}